server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    sql:
      init:
        mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      web-allow-others: false

logging:
  level:
    ROOT: ERROR
#    org.springframework.jdbc: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
