spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://db:5432/db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:changeLog/master.xml
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: ERROR
    liquibase: DEBUG

crossOrigins: http://localhost:3000