spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  liquibase:
    change-log: classpath:changeLog/master.xml
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: ERROR
    liquibase: DEBUG

crossOrigins: http://frontend:3000