spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: ERROR