      create table author (
          id bigint generated by default as identity,
          full_name varchar(255),
          primary key (id)
      );

      create table book (
          id bigint generated by default as identity,
          title varchar(255),
          author_id bigint,
          primary key (id)
      );

      create table books_genres (
          genre_id bigint not null,
          book_id bigint not null
      );

      create table comment (
          id bigint generated by default as identity,
          text varchar(255),
          book_id bigint,
          primary key (id)
      );

      create table genre (
          id bigint generated by default as identity,
          name varchar(255),
          primary key (id)
      );

      alter table if exists book
         add constraint FKklnrv3weler2ftkweewlky958
         foreign key (author_id)
         references author;

      alter table if exists books_genres
         add constraint FK74hohmy8rprauuhhbbdmx9vh9
         foreign key (book_id)
         references genre;

      alter table if exists books_genres
         add constraint FKxg2rd31w1guudd4ox0kfin3p
         foreign key (genre_id)
         references book;

      alter table if exists comment
         add constraint FKkko96rdq8d82wm91vh2jsfak7
         foreign key (book_id)
         references book;