#spring:
#  r2dbc:
#    url: r2dbc:h2:mem:///testdb
#    driver: h2
#    username: sa
#    password: password
#  sql:
#    init:
#      mode: always
#  profiles:
#    active: default
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: ERROR