      create table author (
          id bigint generated by default as identity,
          full_name varchar(255),
          primary key (id)
      );

      create table book (
          id bigint generated by default as identity,
          title varchar(255),
          author_id bigint,
          primary key (id)
      );

      create table books_genres (
          genre_id bigint not null,
          book_id bigint not null
      );

      create table comment (
          id bigint generated by default as identity,
          text varchar(255),
          book_id bigint,
          primary key (id)
      );

      create table users (
          id bigint generated by default as identity,
          username varchar(255),
          password varchar(255),
          roles varchar(255),
          primary key (id)
      );

      create table genre (
          id bigint generated by default as identity,
          name varchar(255),
          primary key (id)
      );

      alter table if exists book
         add constraint fk_book_author
         foreign key (author_id)
         references author;

      alter table if exists books_genres
         add constraint fk_books_genres_book
         foreign key (book_id)
         references book;

      alter table if exists books_genres
         add constraint fk_books_genres_genre
         foreign key (genre_id)
         references genre;

      alter table if exists comment
         add constraint fk_comment_book
         foreign key (book_id)
         references book;